name: linuxai
version: "1.0"
summary: LinuxAI, An artificial intelligence for Linux Desktops
description: LinuxAI is a Sofware for Linux Desktops which is similiar to Google Assistant on Android
grade: stable
confinement: strict

apps:
  linuxai:
    command: bash install.sh

parts:
  gnu-hello:
    plugin: autotools
    source: https://github.com/agrawal-prateek/linuxAI/blob/master/linuxAI.zip
